package com.xxn.sport.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "INTEGRAL_GAINED".
 */
public class IntegralGained {

    private String uid;
    private String useId;
    private String gainTime;
    private Integer integral;
    private Integer gainReason;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IntegralGained() {
    }

    public IntegralGained(String uid, String useId, String gainTime, Integer integral, Integer gainReason) {
        this.uid = uid;
        this.useId = useId;
        this.gainTime = gainTime;
        this.integral = integral;
        this.gainReason = gainReason;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUseId() {
        return useId;
    }

    public void setUseId(String useId) {
        this.useId = useId;
    }

    public String getGainTime() {
        return gainTime;
    }

    public void setGainTime(String gainTime) {
        this.gainTime = gainTime;
    }

    public Integer getIntegral() {
        return integral;
    }

    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    public Integer getGainReason() {
        return gainReason;
    }

    public void setGainReason(Integer gainReason) {
        this.gainReason = gainReason;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
