package com.xxn.sport.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SPORT_RECORD_TMP".
 */
public class SportRecordTmp {

    private String uid;
    private String userID;
    private Integer sportType;
    private String startTime;
    private String endTime;
    private Integer pauseTime;
    private String motionTrack;
    private Float distance;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SportRecordTmp() {
    }

    public SportRecordTmp(String uid, String userID, Integer sportType, String startTime, String endTime, Integer pauseTime, String motionTrack, Float distance) {
        this.uid = uid;
        this.userID = userID;
        this.sportType = sportType;
        this.startTime = startTime;
        this.endTime = endTime;
        this.pauseTime = pauseTime;
        this.motionTrack = motionTrack;
        this.distance = distance;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public Integer getSportType() {
        return sportType;
    }

    public void setSportType(Integer sportType) {
        this.sportType = sportType;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public Integer getPauseTime() {
        return pauseTime;
    }

    public void setPauseTime(Integer pauseTime) {
        this.pauseTime = pauseTime;
    }

    public String getMotionTrack() {
        return motionTrack;
    }

    public void setMotionTrack(String motionTrack) {
        this.motionTrack = motionTrack;
    }

    public Float getDistance() {
        return distance;
    }

    public void setDistance(Float distance) {
        this.distance = distance;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
