package com.xxn.sport.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xxn.sport.entities.IntegralGained;
import com.xxn.sport.entities.SportRecord;
import com.xxn.sport.entities.SportRecordTmp;

import com.xxn.sport.dao.IntegralGainedDao;
import com.xxn.sport.dao.SportRecordDao;
import com.xxn.sport.dao.SportRecordTmpDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig integralGainedDaoConfig;
    private final DaoConfig sportRecordDaoConfig;
    private final DaoConfig sportRecordTmpDaoConfig;

    private final IntegralGainedDao integralGainedDao;
    private final SportRecordDao sportRecordDao;
    private final SportRecordTmpDao sportRecordTmpDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        integralGainedDaoConfig = daoConfigMap.get(IntegralGainedDao.class).clone();
        integralGainedDaoConfig.initIdentityScope(type);

        sportRecordDaoConfig = daoConfigMap.get(SportRecordDao.class).clone();
        sportRecordDaoConfig.initIdentityScope(type);

        sportRecordTmpDaoConfig = daoConfigMap.get(SportRecordTmpDao.class).clone();
        sportRecordTmpDaoConfig.initIdentityScope(type);

        integralGainedDao = new IntegralGainedDao(integralGainedDaoConfig, this);
        sportRecordDao = new SportRecordDao(sportRecordDaoConfig, this);
        sportRecordTmpDao = new SportRecordTmpDao(sportRecordTmpDaoConfig, this);

        registerDao(IntegralGained.class, integralGainedDao);
        registerDao(SportRecord.class, sportRecordDao);
        registerDao(SportRecordTmp.class, sportRecordTmpDao);
    }
    
    public void clear() {
        integralGainedDaoConfig.getIdentityScope().clear();
        sportRecordDaoConfig.getIdentityScope().clear();
        sportRecordTmpDaoConfig.getIdentityScope().clear();
    }

    public IntegralGainedDao getIntegralGainedDao() {
        return integralGainedDao;
    }

    public SportRecordDao getSportRecordDao() {
        return sportRecordDao;
    }

    public SportRecordTmpDao getSportRecordTmpDao() {
        return sportRecordTmpDao;
    }

}
